# Generated by Django 4.2.2 on 2023-07-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='valor',
            new_name='valor_planejamento',
        ),
    ]
